name: spectra
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - charset-normalizer=3.3.2
  - colorama=0.4.4
  - cyrus-sasl=2.1.28
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.7.1
  - gettext=0.21.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - ipython_pygments_lexers=1.1.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - krb5=1.20.1
  - libabseil=20250127.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.14.1
  - libcxx=19.1.7
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libxml2=2.13.8
  - llvm-openmp=19.1.7
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - mysql=8.4.0
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.0.17
  - pandoc=2.12
  - pandocfilters=1.5.0
  - pcre2=10.42
  - pip=25.2
  - prometheus_client=0.21.1
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyproject_hooks=1.0.0
  - pyqt=5.15.10
  - python=3.11.13
  - python-fastjsonschema=2.20.0
  - qt-main=5.15.2
  - readline=8.3
  - readme_renderer=40.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - tk=8.6.15
  - tqdm=4.63.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - annotated-types==0.7.0
    - anyio==4.7.0
    - appnope==0.1.4
    - argon2-cffi-bindings==21.2.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.16.0
    - backports-tarfile==1.2.0
    - beautifulsoup4==4.13.4
    - bleach==6.2.0
    - build==0.10.0
    - certifi==2025.8.3
    - cffi==1.17.1
    - click==8.2.1
    - cmarkgfm==2024.11.20
    - comm==0.2.1
    - debugpy==1.8.11
    - docutils==0.21.2
    - edn-format==0.7.5
    - fastjsonschema==2.20.0
    - fuzzywuzzy==0.18.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - id==1.5.0
    - idna==3.7
    - importlib-metadata==8.7.0
    - ipykernel==6.29.5
    - ipython==9.1.0
    - ipython-pygments-lexers==1.1.1
    - ipywidgets==8.1.5
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - json5==0.9.25
    - jsonschema==4.25.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.8.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.16.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.15
    - keyring==25.6.0
    - loguru==0.7.3
    - markdown-it-py==4.0.0
    - markupsafe==3.0.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==3.1.2
    - more-itertools==10.8.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.4.4
    - notebook-shim==0.2.4
    - overrides==7.4.0
    - packaging==25.0
    - parso==0.8.4
    - pexpect==4.9.0
    - pkginfo==1.12.0
    - platformdirs==4.3.7
    - ply==3.11
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.43
    - psutil==5.9.0
    - pyarmor==9.1.9
    - pyarmor-cli-core==7.6.8
    - pyarmor-cli-core-darwin==7.6.8
    - pyarmor-cli-core-linux==7.6.8
    - pyarmor-cli-core-windows==7.6.8
    - pydantic==2.11.9
    - pydantic-core==2.33.2
    - pygments==2.19.1
    - pyparsing==3.2.4
    - pyproject-hooks==1.0.0
    - pyqt5==5.15.10
    - pyqt5-sip==12.13.0
    - pyrfc3339==2.1.0
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - qtconsole==5.6.1
    - qtpy==2.4.1
    - readme-renderer==40.0
    - referencing==0.30.2
    - requests==2.32.4
    - requests-toolbelt==1.0.0
    - rfc3339-validator==0.1.4
    - rfc3986==2.0.0
    - rfc3986-validator==0.1.1
    - rich==14.1.0
    - rpds-py==0.22.3
    - send2trash==1.8.2
    - setuptools==78.1.1
    - shadowprover==1.2.56
    - sip==6.7.12
    - six==1.17.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - terminado==0.17.1
    - tinycss2==1.4.0
    - tornado==6.5.1
    - traitlets==5.14.3
    - twine==6.2.0
    - typing-extensions==4.12.2
    - typing-inspection==0.4.1
    - urllib3==1.26.20
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.45.1
    - widgetsnbextension==4.0.13
    - zipp==3.23.0

